- platform: nut
  name: UPS Office
  host: !secret ip_ups_office
  username: monuser
  password: secret
  resources:
    - battery.charge
    - ups.load
    - input.voltage
    - ups.status
    - ups.temperature
    - battery.voltage
