- platform: synologydsm
  host: !secret office_nas_ip
  username: !secret office_nas_username
  password: !secret office_nas_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    #- network_up
    #- disk_status
    #- disk_temp
    #- volume_percentage_used
