- platform: command_line
  command: python3 /var/services/homes/luar/playground/homeassistant/scripts/get_power_consumption.py
  name: Power Consumption
  unit_of_measurement: "Watts"
  value_template: '{{ value_json.result | multiply(0.1) }}'
