- id: telegram_list
  alias: telegram_command list
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /commands
  action:
  - service: notify.telegram
    data:
      message: commands
      data:
        keyboard:
        - /rack_fans_off, /rack_fans_on
        - /luz_comedor_off, /luz_comedor_on
        - /ping, /status
- id: telegram_ping
  alias: Telegram command that reply pong to ping
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
  - service: notify.telegram
    data:
      message: pong
- id: telegram_status
  alias: Telegram command that reply status
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /status
  action:
  - service: notify.telegram
    data:
      message: "Rack temp: {{ states.sensor.rack_temperature.state }} \xBAC\nRack\
        \ humidity: {{ states.sensor.rack_humidity.state }} %\nOffice temp: {{ states.sensor.office_temperature.state\
        \ }} \xBAC\nRack fans: {{ states.switch.rack_fans.state }}\nLuz del comedor:\
        \ {{ states.switch.luz_comedor.state }}\nTemperatura CPU: {{ states.sensor.cpu_temperature.state\
        \ }}\nCalefon: {% \n   if (states.switch.calefon.attributes.state_detail=='on')\
        \ \n%}Calentando ({{ states.switch.calefon.attributes.current_power_w }} W){%\
        \ \n   elif (states.switch.calefon.attributes.state_detail=='standby') \n\
        %}No calentando{% \n   elif (states.switch.calefon.attributes.state_detail=='standby')\
        \ \n%}Apagado{% \n   else\n%}Desconocido{%   \n   endif %} \n"
- id: telegram_luz_comedor_on
  alias: 'Telegram command: prender luz del comedor'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /luz_comedor_on
  action:
  - service: homeassistant.turn_on
    entity_id: switch.luz_comedor
  - service: notify.telegram
    data:
      message: Luz del comedor turned on.
- id: telegram_luz_comedor_off
  alias: 'Telegram command: apagar luz del comedor'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /luz_comedor_off
  action:
  - service: homeassistant.turn_off
    entity_id: switch.luz_comedor
  - service: notify.telegram
    data:
      message: Luz del comedor turned off.
- id: telegram_rack_fans_on
  alias: 'Telegram command: start rack fans'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /rack_fans_on
  action:
  - service: homeassistant.turn_on
    entity_id: switch.rack_fans
  - service: notify.telegram
    data:
      message: Rack fans turned on.
- id: telegram_rack_fans_off
  alias: 'Telegram command: stop rack fans'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /rack_fans_off
  action:
  - service: homeassistant.turn_off
    entity_id: switch.rack_fans
  - service: notify.telegram
    data:
      message: Rack fans turned off.
- id: telegram_avisar_llega_tesa
  alias: Avisar por telegram cuando llega mi madre
  trigger:
    platform: state
    entity_id: !secret xperia_device
    from: 'not_home'
    to: 'home'
    for:
      minutes: 10
  action:
    service: notify.telegram
    data:
      message: Mama volvio a casa
- id: telegram_avisar_sale_tesa
  alias: Avisar por telegram cuando se va mi madre de casa
  trigger:
    platform: state
    entity_id: !secret xperia_device
    from: 'home'
    to: 'not_home'
    for:
      minutes: 10
  action:
    service: notify.telegram
    data:
      message: Mama salio de casa
- id: telegram_homeassistant_updates
  alias: Hay actualizaciones de HomeAssistant
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.telegram
    data:
      message: There is a new Home Assistant release available.
- id: prender_luz_comedor
  alias: Prender la luz del comedor
  trigger:
    platform: sun
    event: sunset
    offset: +00:25:00
  action:
    service: homeassistant.turn_on
    entity_id: switch.luz_comedor
- id: apagar_luz_comedor
  alias: Apagar la luz del comedor
  trigger:
    platform: sun
    event: sunrise
    offset: -00:35:00
  action:
    service: homeassistant.turn_off
    entity_id: switch.luz_comedor
- id: temp_rack_alta
  alias: Temp Rack Alta
  trigger:
    platform: numeric_state
    entity_id: sensor.rack_temperature
    above: 32.0
  condition:
    condition: state
    entity_id: switch.rack_fans
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id:
    - switch.rack_fans
  - service: notify.telegram
    data:
      message: "Turning on rack fans, T:{{ states.sensor.rack_temperature.state }}\xBA\
        C H:{{ states.sensor.rack_humidity.state }}%"
- id: temp_rack_baja
  alias: Temp Rack Baja
  trigger:
    platform: numeric_state
    entity_id: sensor.rack_temperature
    below: 28
  condition:
    condition: state
    entity_id: switch.rack_fans
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - switch.rack_fans
  - service: notify.telegram
    data:
      message: "Turning off rack fans, T:{{ states.sensor.rack_temperature.state }}\xBA\
        C H:{{ states.sensor.rack_humidity.state }}%"
- id: homeassistant_starts
  alias: Inicia HomeAssistant
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: notify.telegram
    data:
      message: Home Assistant is starting.
- id: calefon_on
  alias: Prendio el Calefon
  trigger:
    platform: template
    value_template: '{% if (states.switch.calefon.attributes.state_detail==''on'')
      %}true{% else %}false{% endif %}'
  action:
  - service: notify.telegram
    data:
      message: 'Prendio el calefon, consumo: {{ states.switch.Calefon.attributes.current_power_w
        }} watts'
- id: calefon_off
  alias: Se apago el Calefon
  trigger:
    platform: template
    value_template: '{% if (states.switch.calefon.attributes.state_detail==''standby'')
      %}true{% else %}false{% endif %}'
  action:
  - service: notify.telegram
    data:
      message: 'Apago el calefon, consumo: {{ states.switch.Calefon.attributes.current_power_w
        }} watts'
- action:
  - alias: Rack UPS on Battery notification.
    data:
      message: Rack UPS is on Battery.
    service: notify.telegram
  alias: Notify when Rack UPS is on battery
  id: '1497919127277'
  trigger:
  - entity_id: sensor.ups_status
    from: ONLINE
    platform: state
    to: ONBATT

- action:
  - alias: Office UPS on Battery notification.
    data:
      message: Office UPS is on Battery.
    service: notify.telegram
  alias: Notify when Office UPS is on battery
  id: '1497919127278'
  trigger:
  - entity_id: sensor.nut_ups_status_data
    from: OL
    platform: state
    to: OB

- action:
  - alias: Rack UPS on Line Power notification.
    data:
      message: Rack UPS is on Line Power.
    service: notify.telegram
  alias: Notify when Rack UPS is on Line Power
  id: '1497919127277'
  trigger:
  - entity_id: sensor.ups_status
    from: ONBATT
    platform: state
    to: ONLINE

- action:
  - alias: Office UPS on Line Power notification.
    data:
      message: Office UPS is on Line Power.
    service: notify.telegram
  alias: Notify when Office UPS is on line power
  id: '1497919127278'
  trigger:
  - entity_id: sensor.nut_ups_status_data
    from: OB
    platform: state
    to: OL
