homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone

recorder:
  purge_days: 8
  db_url: !secret db_url

frontend:

http:
  api_password: !secret api_password
  server_port: 8123
  base_url: !secret base_url

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

mqtt:
  broker: homeassistant

influxdb:
  host: !secret main_server
  database: homeassistant

apcupsd: 
  host: !secret main_server

config:

notify: !include notify.yaml
automation: !include automations.yaml
telegram_bot: !include telegram_bot.yaml
device_tracker: !include device_tracker.yaml

group: !include_dir_merge_named groups/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
