homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

recorder:
  purge_days: 8
  db_url: !secret db_url

frontend:

http:
  api_password: !secret api_password
  server_port: 8123
  base_url: !secret base_url

updater:
  include_used_components: true

discovery:

conversation: !include conversation.yaml

shopping_list:

history:

logbook:

sun:

mqtt:
  broker: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password

influxdb:
  host: !secret main_server
  database: homeassistant

config:

notify: !include notify.yaml
telegram_bot: !include telegram_bot.yaml
device_tracker: !include device_tracker.yaml

automation: !include_dir_merge_list automations/
group: !include_dir_merge_named groups/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
